### ISSUE TITLE
Do not offer Flatpak for systems that do not have Flatpak capability

### ISSUE THREAD

**Issue by quozl** [sugarlabs/aslo-v4#24]
Detailed view of an activity can show a Flatpak section.  This is harmful for systems that do not have a Flatpak capability.  Either verify with Browse that the capability exists, or disable.

**Comment by srevinsaju** [comment]
I do not know how to fix this. You can optionally disable `flatpak` support by removing the `--include-flatpaks` command line argument, to disable flatpak support completely. 

I will keep this issue open, in case anyone knows how to fix it :smile:

**Comment by srevinsaju** [comment]
@quozl by the way, which are those systems that do not support Flatpak? Do you mean Micorsoft Windows / macOS ?

**Comment by quozl** [comment]
Sugar with Browse doesn't support Flatpak.

It could be fixed by disabling Flatpak content on the detailed view when Browse is detected.

It could also be fixed by adding Flatpak support to Sugar and Browse.

**Comment by srevinsaju** [comment]
Wait, I don't understand. Downloading `.flatpakref` works on Browse Activity for me.

**Comment by srevinsaju** [comment]
@tchx84 what would you suggest as a fix for this issue?

**Comment by tchx84** [comment]
> Detailed view of an activity can show a Flatpak section. This is harmful for systems that do not have a Flatpak capability. Either verify with Browse that the capability exists, or disable.

Can you elaborate on how this is harmful ?

**Comment by srevinsaju** [comment]
Well, I do not know, maybe what @Quozl suggests is https://github.com/sugarlabs-appstore/aslo-v4/issues/24#issuecomment-675270520

**Comment by quozl** [comment]
I can't reproduce now; when I open https://sugarstore.netlify.app/ in Browse, the search doesn't work.

**Comment by srevinsaju** [comment]
Looks like I exceeded the slug size for netlify, I would not be able to push to netlify. I tried to push to `gh-pages`, but seems like I cannot deploy items to gh-pages without enabling GIT LFS. For demonstration purposes, I could deploy aslov4 to my `~/public_html` folder on sunjammer. Is it okay to deploy it there?

**Comment by srevinsaju** [comment]
Alternatively, we could build it on our personal system too, if you have a lot of Sugar Activity clones, (and obviously you would have many). I tested the new one, it works, but I will have to look for another, static site hosting service (where I have not reached build limits)

**Comment by quozl** [comment]
I don't know what you mean about netlify or gh-pages.  Using sunjammer would be a step in the right direction to support the _uploading of bundles by SSH_ [requirement](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2020.md#sugar-app-store-for-python-3-activities-aslov4).  At the moment your test instance goes beyond these requirements and tries to capture all activities on GitHub; that's not something I want (the activities are not necessarily supported), so the way it does it gets in the way of my testing.  I have a long term plan to fork and remove that feature, but I haven't had time to do it yet, sorry.  

We're also not getting involvement from any other Sugar activity developers, and that concerns me.  Perhaps because the repository is not watched by them, and that collaboration is happening only in the repository instead of by mailing list.  We need to find out why the other Sugar activity developers are not involved.

**Comment by srevinsaju** [comment]
@quozl I do not know what you mean. I have already spoken about it in #6 , and on the README.md, I have added the documentation on how to do it. For demonstration purposes, I hosted it on netlify and github pages, I started showing the demo, before I got a shell account. 

>  At the moment your test instance goes beyond these requirements and tries to capture all activities on GitHub

At the moment, I do not have a collection of bundles to extract the metadata from; So I had to clone all the activities from github to build an xo. When I get information on where developers will upload their bundles, I could use them too. Maybe, @quozl, you could upload a few test bundles to `sunjammer`, so I could build it on `sunjammer`, everything would be transparent then. 

> I have a long term plan to fork and remove that feature, but I haven't had time to do it yet, sorry.

Yes you may. Its just a direct way of doing things. Providing the real git clones, have a lot of advantages, like getting the recent commit messages, get the authors and the number of commit messages, etc. A zipped `.xo` looses all these potential information. I have tested building directly from bundles (.xo) and not from clones. and it works :tada:. During that time, I also added a feature, where you could provide the the authors list

See https://github.com/sugarlabs-appstore/aslo-v4/blob/31553411dbc4529e85408a851a7dd8533f600301/aslo4/bundle/bundle.py#L614-L640, extensive docs :smile:

```bash
git -P --log --pretty=format:"%an" > org.laptop.Pippy.log
```
aslo4 generator, automatically reads this file if it exists. Right now, I am putting all the effort in getting all the info, at one place. Thats the mess. When all the developers provide the bundles, things are going to be really easy! 

> We're also not getting involvement from any other Sugar activity developers, and that concerns me. Perhaps because the repository is not watched by them, and that collaboration is happening only in the repository instead of by mailing list. We need to find out why the other Sugar activity developers are not involved.

Well, I could continue the discussion on the mailing list. I do not have any topic to start with, if you do, I can get hold of the thread and move the conversation to mailing list!

:smile: G'day!

**Comment by quozl** [comment]
> At the moment, I do not have a collection of bundles to extract the metadata from; So I had to clone all the activities from github to build an xo. When I get information on where developers will upload their bundles, I could use them too. Maybe, @quozl, you could upload a few test bundles to `sunjammer`, so I could build it on `sunjammer`, everything would be transparent then.

I think we're waiting for you to tell us how to upload.

Our [documentation on activity maintenance](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#checklist---maintainer) says what is needed at the moment.  Can you suggest a change?

At the moment, developers upload Python 2 bundles to https://activities.sugarlabs.org directly. I also upload Python 2 bundles to http://download.laptop.org/activities/ and add them to an index on http://wiki.laptop.org/go/Activities ... I've been formally uploading Python 3 activity tarballs to https://download.sugarlabs.org/sources/ ... I've been informally uploading Python 3 bundles to https://people.sugarlabs.org/~quozl/ but the directory is a mix of Python 2 and Python 3 bundles, so isn't suitable for purpose.  people.sugarlabs.org is hosted on sunjammer.

> > I have a long term plan to fork and remove that feature, but I haven't had time to do it yet, sorry.
> 
> Yes you may. Its just a direct way of doing things. Providing the real git clones, have a lot of advantages, like getting the recent commit messages, get the authors and the number of commit messages, etc. A zipped `.xo` looses all these potential information.

Thanks, but I don't think the target user needs that information.  It's not in the bundles because we don't need it.  It can be derived from a bundle by following the _repository_ metadata.

Perhaps you're thinking of a web site for use by developers; that's not my goal.

> I have tested building directly from bundles (.xo) and not from clones. and it works tada. During that time, I also added a feature, where you could provide the the authors list

Thanks, I guess.  :grin:

> 
> See
> 
> https://github.com/sugarlabs-appstore/aslo-v4/blob/31553411dbc4529e85408a851a7dd8533f600301/aslo4/bundle/bundle.py#L614-L640
> , extensive docs smile
> 
> ```shell
> git -P --log --pretty=format:"%an" > org.laptop.Pippy.log
> ```
> 
> aslo4 generator, automatically reads this file if it exists. Right now, I am putting all the effort in getting all the info, at one place. Thats the mess. When all the developers provide the bundles, things are going to be really easy!
> 
> > We're also not getting involvement from any other Sugar activity developers, and that concerns me. Perhaps because the repository is not watched by them, and that collaboration is happening only in the repository instead of by mailing list. We need to find out why the other Sugar activity developers are not involved.
> 
> Well, I could continue the discussion on the mailing list. I do not have any topic to start with, if you do, I can get hold of the thread and move the conversation to mailing list!
> 
> smile G'day!

We don't seem to get traction on mailing list either; perhaps spam filtering is stopping discussion.  It may be best to identify the most recent activity maintainers and reach out to them.

**Comment by srevinsaju** [comment]
@quozl deployed it to sunjammer

Links here https://people.sugarlabs.org/~srevinsaju/aslo

To deploy a single bundle

```bash

# Build the bundle
python3 setup.py dist_xo

 # send the bundle using rsync / scp
rsync -r dist/JupyterLabs-6.xo srevinsaju@shell.sugarlabs.org:/home/srevinsaju/aslo/bundles/.

# optional 
# provide the link to github repository
git config --get remote.origin.url > io.srevinsaju.JupyterLabs.git
rsync -r io.srevinsaju.JupyterLabs.git srevinsaju@shell.sugarlabs.org:/home/srevinsaju/aslo/bundles/.


# optional 
# provide the list of authors
git -P log --pretty=format:"%an" > io.srevinsaju.JupyterLabs.log
rsync -r io.srevinsaju.JupyterLabs.log srevinsaju@shell.sugarlabs.org:/home/srevinsaju/aslo/bundles/.


# ssh into sunjammer 
# trigger a build

python3 -m aslo4 -vfsguy -p ~/aslo-v4/aslo4-static -x https://people.sugarlabs.org/\~srevinsaju/aslo -i /home/srevinsaju/aslo/bundles -o ~/public_html/aslo
```

@quozl as you have root, you may write to ~/aslo/bundles I guess. Feel free to let me know of any changes I have to make.

Making path relative might have broken some stuff, please test the new builds, I have tested most parts, in case I have missed any. Thanks

**Comment by srevinsaju** [comment]
@quozl deployed it to sunjammer

Links here https://people.sugarlabs.org/~srevinsaju/aslo

To deploy a single bundle

```bash

# Build the bundle
python3 setup.py dist_xo

 # send the bundle using rsync / scp
rsync -r dist/JupyterLabs-6.xo <my_username>@xxx.xxx.org:/home/<my_username>/aslo/bundles/.

# optional 
# provide the link to github repository
git config --get remote.origin.url > io.srevinsaju.JupyterLabs.git
rsync -r io.srevinsaju.JupyterLabs.git <my_username>@xxx.xxx.org:/home/<my_username>/aslo/bundles/.


# optional 
# provide the list of authors
git -P log --pretty=format:"%an" > io.srevinsaju.JupyterLabs.log
rsync -r io.srevinsaju.JupyterLabs.log <my_username>@xxx.xxx.org:/home/<my_username>/aslo/bundles/.


# ssh into sunjammer 
# trigger a build

python3 -m aslo4 -vfsguy -p ~/aslo-v4/aslo4-static -x https://people.sugarlabs.org/\~srevinsaju/aslo -i /home/<my_username>/aslo/bundles -o ~/public_html/aslo
```

@quozl as you have root, you may write to ~/aslo/bundles I guess. Feel free to let me know of any changes I have to make.

Making path relative might have broken some stuff, please test the new builds, I have tested most parts, in case I have missed any. Thanks

**Comment by quozl** [comment]
Thanks.  Separate issues created.  Back to this issue, can you add a bundle that shows the problem?

**Comment by srevinsaju** [comment]
Hmm, Implode activity exists on flatpak. you could add a `com.jotaro.*.ImplodeActivity.git` with the output of
```bash
git config --get remote.origin.url > com.jotaro...Implode.git
```

I don't remember the exact bundle name. 
Re running the build will automatically fetch the flatpak data and include the card with flatpak options

**Comment by quozl** [comment]
Okay, thanks.  As I'm not going to be building from git, this is no longer a problem.
