### ISSUE TITLE
Do not show compatible python or sugar version

### ISSUE THREAD

**Issue by quozl** [sugarlabs/aslo-v4#45]
https://people.sugarlabs.org/~srevinsaju/aslo/ has icons (a child icon with a 3) that serve no purpose for the target audience; they aren't expected to know the version of Sugar or the version of Python on their computer.

**Comment by srevinsaju** [comment]
Great. I will remove that!

**Comment by srevinsaju** [comment]
Ok, looks like I no longer have write access to this repo

**Comment by quozl** [comment]
Added you with _maintain_ access.
