### ISSUE TITLE
Bundle listener or worker

### ISSUE THREAD

**Issue by quozl** [sugarlabs/aslo-v4#46]
At the moment to add a bundle to the test instance on sunjammer, we have to su as root, then sudo as srevinsaju, and run this command;

```log
python3 -m aslo4 -vfsguy -p ~/aslo-v4/aslo4-static -x https://people.sugarlabs.org/\~srevinsaju/aslo -i /home/srevinsaju/aslo/bundles -o ~/public_html/aslo
```

It could instead be in a periodic crontab job that checks for new bundles, or a job using `inotifywait`.

**Comment by srevinsaju** [comment]
I got chmod the directory to make it o+rw for all
I guess this would do
```bash
chmod -R o+rw,g+rw ./aslo
```
I am not sure. It should work right? I am less experienced with chmod.

Alternatively, what I would have done is to create another user, say `aslo` and, give all the privelleges to `aslo` to an `aslo` directory, and then enable local crontab for aslo. Adding users to a `aslo` group, and giving them read write access, would also work.

The sunjammer instance, does not have `pip3`. I had to bootstrap pip from pypa, as I am not su. Maybe, as root, you cold install `python3-pip`, as it will then be available to all.

**Comment by quozl** [comment]
Thanks.  I've installed `python3-pip`.

Group `sugardl` is assigned to each user who releases activities.  I've used `chgrp` on `bundles`, removed world write, and tested I can write files as my non-root user.

```log
sunjammer:/home/srevinsaju/aslo# chgrp sugardl bundles
sunjammer:/home/srevinsaju/aslo# chmod -R o-w bundles
...
quozl@sunjammer:~$ touch /home/srevinsaju/aslo/bundles/test
quozl@sunjammer:~$ rm /home/srevinsaju/aslo/bundles/test
```

**Comment by srevinsaju** [comment]
@quozl Can you also allow the `sugardl` members to install a `pip` package globally. Right now, `aslo-v4` generator is installed to `/home/srevinsaju/.local/lib/python3.x/site-packages/aslo4`.If I could install it globally, i.e, to `/usr` or to any specific directory, and extend `PYTHONPATH` to that directotry, so that you could also use the `aslo4` bundle without `su` as `srevinsaju` ?

**Comment by srevinsaju** [comment]
I did that for my sibling, by allowing executing a particular app, say `pip`, for group `sugardl` as `root` by editing /etc/sudoers. But possibly, there are better solutions too.

**Comment by srevinsaju** [comment]
I guess, we could move this repository to `sugarlabs` github repo. It guess, it attained some stability now

**Comment by quozl** [comment]
I think it is more secure if the builder is run in a separate account, such as yours, that's why I mentioned `inotifywait` and `crontab`.

Experiment with this;

* write a shell script `bin/aslo-rebuild` that does what you need; i.e. run the builder once then exit,
* test it at the shell prompt until it works,
* test it as a detached job;
```log
echo bin/aslo-rebuild | batch
```
* check the logs that are mailed to you, to see that it worked,
* add it as a per hour crontab,
```log
% crontab -e
0 * * * * bin/aslo-rebuild
[save and exit your editor]
```
* add locking to your script so that it fails if it tries to run at the same time as itself; `flock`.

**Comment by quozl** [comment]
Try moving the repository.  You're a member of `sugarlabs` at the moment, and I guess that should be enough privs.  If not, make me an owner here, let me know, and I'll try it.

**Comment by quozl** [comment]
https://github.com/sugarlabs-appstore/aslo-v4/settings "danger zone" ... "transfer".  Let me know.

**Comment by srevinsaju** [comment]
@quozl looks like someone forked it already to `sugarlabs`. So I cannot transfer it. It would be great, if I could transfer issues along with the repository.

**Comment by srevinsaju** [comment]
I guess, I cannot transfer issues across forks.

**Comment by quozl** [comment]
I deleted the fork and transferred the repository.

**Comment by srevinsaju** [comment]
Thanks :smile:

**Comment by srevinsaju** [comment]
@quozl I created the shell script, and followed your instructions. It has mailed me the result, it works. I have added the shellscript to crontab too.

**Comment by srevinsaju** [comment]
@quozl I did not understand this line

> add locking to your script so that it fails if it tries to run at the same time as itself; flock.

By locking, do you mean, what happens when you try to use `apt` while another instance is running, it tells: Failed to get apt.lock .. is this the same thing?

**Comment by srevinsaju** [comment]
Would this do? `flock aslo -c 'bin/aslo-rebuild'`

**Comment by srevinsaju** [comment]
@quozl I got my first mail from cron :tada:

**Comment by quozl** [comment]
You can test `flock` by temporarily adding a call to `time.sleep(30)` in your Python code; that will give you 30 seconds to try conflicting.

In scripts, it can be easier to use `flock` with file descriptor redirection, like so;

```bash
#!/bin/bash
set -e
(
    flock -w 300 9 || exit 1
    python3 something.py
) 9>aslo.lock
```

This example waits for five minutes for the lock, and then fails if the lock could not be acquired.

Should you get sick of the mail, change your script to redirect stdout to a log file.  A cron job that emits nothing generates no mail.

**Comment by srevinsaju** [comment]
Thanks. I were having a school test on Python. I was away for some time. Thanks for explaining this to me. I have learnt a lot in just 3 days. Thanks to you :smile:

**Comment by srevinsaju** [comment]
@quozl I added the `flock` command in the shell script

**Comment by srevinsaju** [comment]
> Should you get sick of the mail, change your script to redirect stdout to a log file. A cron job that emits nothing generates no mail.

I removed the `-v` verbose option on the static generator. I guess that would be verbose too. I have to add a `--silent` option to raise only errors

**Comment by srevinsaju** [comment]
@quozl Done. Fixed all other bugs too!  Please review :D

**Comment by quozl** [comment]
As a test, I've uploaded Browse bundle, but there was no change to http://people.sugarlabs.org/~srevinsaju/aslo/ ... I did not investigate further.

**Comment by srevinsaju** [comment]
Cron job is set for an interval of 2 hours I guess, I ran
```
echo bin/aslo-rebuild | batch
```
for demonstration, please check again

**Comment by quozl** [comment]
Yay, thanks.
