### ISSUE TITLE
Rendering fail

### ISSUE THREAD

**Issue by quozl** [sugarlabs/aslo-v4#54]
Content is overlapping.  On Ubuntu 20.04 with Browse;

![Screenshot_uff_2020-09-21_10:22:10](https://user-images.githubusercontent.com/2936481/93725677-5d0dd100-fbf4-11ea-9ff5-3f371ff90733.png)

On Ubuntu 18.04 with Firefox;

![tmp](https://user-images.githubusercontent.com/2936481/93725708-80d11700-fbf4-11ea-8347-8e0d347edd9b.png)

Also click on activities does not take browser to activity page.

**Comment by srevinsaju** [comment]
I agree, I checked today morning. I forgot to apply `sunjammer_srevinsaju_aslo_catalog.patch`, should be fixed now

**Comment by quozl** [comment]
Thanks, is fixed.
