### ISSUE TITLE
Activity cards render incorrectly, theme switch broken

### ISSUE THREAD

**Issue by shaansubbaiah** [sugarlabs/aslo-v4#60]
In https://sugarstore.netlify.app, the Activity images are out of place, and switching themes doesn't work.

I have a bunch of addons that block scripts and ads on Firefox so I tried it on stock Chromium as well, got the same results.

Let me know if the link I used 'sugarstore.netlify.app', is outdated (it was linked in the repository description) and if any other information is required.  

**Firefox 80.0.1**
![image](https://user-images.githubusercontent.com/11163839/94795815-85b77700-03fb-11eb-8bb6-b2508ec59b14.png)

**Chromium 85.0.4183.102**

![image](https://user-images.githubusercontent.com/11163839/94795696-53a61500-03fb-11eb-9ba2-119308944cf2.png)

**Comment by srevinsaju** [comment]
Thanks, the link is deprecated. I might as well deprecate it to 404.
The new link is https://people.sugarlabs.org/~srevinsaju/aslo/

**Comment by srevinsaju** [comment]
My slug limit on Netlify is reached. So we are now deploying to [sunjammer[(https://sunjammer.sugarlabs.org)

**Comment by shaansubbaiah** [comment]
Thanks, this works much better, I like the new look. 
Am I missing something or are there only 3 activities?

**Comment by srevinsaju** [comment]
No, only three, one maintained by me, and two by @quozl . We are waiting for maintainers to submit xo's :)

**Comment by shaansubbaiah** [comment]
Thanks, closing 👍
