### ISSUE TITLE
release announcement review

### ISSUE THREAD

**Issue by quozl** [sugarlabs/aslo-v4#64]
Here's a release announcement message, as shown by mutt(1);

```log
Implode-20.1.1~quozl has been released

Version: 20.1.1~quozl
Bundle ID: com.jotaro.ImplodeActivity
Release time: Thu Jan 21 04:12:57 2021

You can download the latest release of this activity here:
  - Info: https:///app/com.jotaro.ImplodeActivity
  - Download: https:///bundles/Implode-20.1.1~quozl.xo

If you have questions about this review, please answer to this e-mail or join
+#sugar on chat.freenode.net.
--
Sugar Activity Library
https://
```

* [ ] the release time was not the time on the file, but the time of execution,
* [x] the info, download and footer links don't work (missing host name),
* [ ] new in this version and changelog are not present,
* [ ] it isn't clear to whom activities-v4@ mail is directed,
* [ ] wrap the text to fit character-cell mail convention, [RFC2646](https://tools.ietf.org/html/rfc2646) may be of interest.

**Comment by srevinsaju** [comment]
> * [ ]  the release time was not the time on the file, but the time of execution,

The release time: is it embedded within the XO? Can I extract that from the XO itself? 
It is recommended that the activity maintainer run `rebuild-aslo` as soon as the bundle is copied into the directory. So, until the activity maintainer runs `rebuild-aslo`, the bundle remains unpublished. Do you think that, next time, on the next release, the time will be correct?

> * [x]  the info, download and footer links don't work (missing host name),

Yes, fixed that in `sunjammer:~activities-v4/src/aslo-v4/aslo4/catalog.py`

> * [ ]  new in this version and changelog are not present,

I can add that. Good suggesstion.

> * [ ]  it isn't clear to whom activities-v4@ mail is directed,

It is not directed to anyone. Any email to `activities-v4@` is simply ignored. Should we alias the email to a maintainer?

> * [ ]  wrap the text to fit character-cell mail convention, [RFC2646](https://tools.ietf.org/html/rfc2646) may be of interest.

Right. Thanks for the link

**Comment by quozl** [comment]
You could deduce the release time from the activity.info file modify time.  `ZipInfo.date_time`

A default reply should go to the activity maintainer.  A reply-all to the mailing list too.  You could deduce from file ownership?
