### ISSUE TITLE
Release announcement date format, and language

### ISSUE THREAD

**Issue by quozl** [sugarlabs/aslo-v4#66]
```log
Release time: 2021-2-3 8:36:36
```

looks strange, as most date times in ISO format use a leading zero in fields.

```log
Release time: 2021-02-03 08:36:36
```

is more expected.

Also, "about this review" is odd, as it isn't a review, but a release.

**Comment by srevinsaju** [comment]
https://github.com/sugarlabs/aslo-v4/blob/e071af059cdbac9bb903b9543beec89033f35cd6/aslo4/generator.py#L943

Tells I used `asctime`. 

This is the jinja2 template for the release email

https://github.com/sugarlabs/aslo-v4/blob/e071af059cdbac9bb903b9543beec89033f35cd6/aslo4-static/templates/release_template.eml#L20

Let me know what's best, or you can make changes yourself. I guess I adapted this email from aslo-v1's release notification, but I am not exactly sure.

**Comment by quozl** [comment]
That's odd.  For me, `asctime` shows 'Wed Feb  3 18:43:05 2021' and is documented not to use locale.

**Comment by srevinsaju** [comment]
Ok, I had been looking at the wrong place. Next build should have it fixed. :smile:
