### ISSUE TITLE
Release Browse-207 ignored

### ISSUE THREAD

**Issue by quozl** [sugarlabs/aslo-v4#67]
Browse-207 was released in the usual way.

`rebuild-aslo` reported
```log
host~$ ssh sunjammer rebuild-aslo
[STATIC][FEED][org.laptop.WebActivity] New release detected 207
[STATIC][FEED][org.laptop.WebActivity] New release detected 206
host~$ █
```

https://v4.activities.sugarlabs.org/app/org.laptop.WebActivity.html shows v206 instead of v207

**Comment by srevinsaju** [comment]
Possibly fixed in #69

**Comment by srevinsaju** [comment]
I apologize for a stream of emails which happened when I was testing :facepalm:

**Comment by srevinsaju** [comment]
Need to improve some instructions. Fixed now.
