### ISSUE TITLE
rebuild-aslo error

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/aslo-v4#79]
Running rebuild aslo on sunjammer throws this error
```python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Opening here to track the issue, noticed it while releasing Cells.

**Comment by quozl** [comment]
What are the values of host and port?

**Comment by quozl** [comment]
Should be a mail server, so it can send mail.

If nothing is missing, find out why mail server is missing?

**Comment by chimosky** [comment]
> Should be a mail server, so it can send mail. If nothing is missing, find out why mail server is missing?

Yep, no mail was sent after the release was made. 

Also noticed my sugarlabs.org alias bouncing and I'll take a look once I can.

**Comment by quozl** [comment]
I've restarted the mail server, try again.

**Comment by chimosky** [comment]
Port 25 is being listened on and everything works fine now, restart to the rescue. Thanks!
